project:
  type: website
  output-dir: _site

website:
  title: "Mohammad Dastgheib"
  site-url: https://mdastgheib.com
  description: "Vision science researcher specializing in perceptual processing and human-computer interaction"
  page-navigation: true
  back-to-top-navigation: true
  twitter-card:
    card-style: summary_large_image
    
  navbar:
    search: true
    right:
      - text: About
        href: about/index.qmd
      - text: Portfolio
        href: portfolio/index.qmd
      - text: Skills
        href: skills/index.qmd
      - text: Research
        href: research/index.qmd
      - text: Publications
        href: publications/index.qmd
      - text: CV
        href: cv.qmd
        
  page-footer:
    left: "© 2024 Mohammad Dastgheib • Built with Quarto"
    center: |
        <a href="mailto:mdast003@ucr.edu" title="Email"><i class="fas fa-envelope"></i></a>
        <a href="https://linkedin.com/in/mdastgheib" title="LinkedIn"><i class="fab fa-linkedin"></i></a>
        <a href="https://scholar.google.com/citations?user=SNVpHcUAAAAJ" title="Google Scholar"><i class="ai ai-google-scholar"></i></a>
        <a href="https://github.com/mohdasti" title="GitHub"><i class="fab fa-github"></i></a>


format:
  html:
    theme:
      light: cosmo
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
          <link rel="stylesheet" href="assets/listing-default.css">
    toc: true
    code-fold: true
    lightbox: true
    
execute:
  freeze: auto