project:
  type: website
  output-dir: _site

website:
  title: "Mohammad Dastgheib"
  site-url: https://mdastgheib.com
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: Research
      - href: publications/index.qmd
        text: Publications
      - href: cv.qmd
        text: CV

format:
  html:
    theme:
      light: trestles
    css: styles.scss
    toc: true
    code-fold: true
    
resources: 
  - "CV/CV_MDastgheib.pdf"


execute:
  freeze: auto