[build]
publish = "_site"
command = """
  wget -qO- https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.549/quarto-1.4.549-linux-amd64.tar.gz | tar -xzv -C .
  export PATH="$PATH:$PWD/quarto-1.4.549/bin"
  quarto render --verbose
"""

[[plugins]]
package = "@quarto/netlify-plugin-quarto"

[build.environment]
GO_VERSION = "1.21.x"