[build]
publish = "_site"
command = """
  wget -q -O quarto.deb https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.549/quarto-1.4.549-linux-amd64.deb && \
  sudo dpkg -i quarto.deb && \
  quarto render
"""

[[plugins]]
package = "@quarto/netlify-plugin-quarto"